### ISSUE TITLE
The fmt-maven-plugin has moved to com.spotify.fmt

### ISSUE THREAD

**Issue by nielsbasjes** [googleapis/java-storage-nio#1069]
The `com.coveo:fmt-maven-plugin` has been moved from https://github.com/coveo/fmt-maven-plugin to https://github.com/spotify/fmt-maven-plugin

The plugin itself has also been moved to `com.spotify.fmt:fmt-maven-plugin`

**Comment by JesseLovelace** [comment]
We get this dependency from java-shared-config, and I believe it's pinned to a specific version due to Java 8 compatibility. I opened a [bug](https://github.com/googleapis/java-shared-config/issues/650) to double check, but since we won't be making any changes here in java-storage-nio I'm going to close this out

**Comment by suztomo** [comment]
@nielsbasjes Is the fmt-maven-plugin causing any issue to you?

**Comment by nielsbasjes** [comment]
> @nielsbasjes Is the fmt-maven-plugin causing any issue to you?

No, no problem right now.

I made this issue because a dependency or plug-in that changes package in this way will become a security problem over time because automatic updates will not be presented.
