### ISSUE TITLE
Provide non-SPI means of obtaining a `Path` from a `gs://blah/lolcat.csv` URI

### ISSUE THREAD

**Issue by reddaly** [googleapis/java-storage-nio#1153]
**Is your feature request related to a problem? Please describe.**
The documentation requires using SPI to create a `Path` as follows:

```java
Paths.get(URI.create("gs://bucket/lolcat.csv"))
```

I don't want to use SPI. I don't understand SPI. I just want a way to get a `Path` given a `gs://blah/lolcat.csv` style URI.

**Describe the solution you'd like**

Please provide some static function that takes a URI and returns a `GoogleStoragePath`

**Comment by BenWhitehead** [comment]
The other APIs of java file nio do need the FileSystem registered via the SPI.

For example, `Files.newByteChannel(Path)` leverages the SPI registered FileSystem in order to know how to open that byte channel.

If you aren't wanting to deal with the Java File NIO api at all, https://github.com/googleapis/java-storage sounds like more of what you'd want. With that library you can something like:
```
Storage s = StorageOptions.newBuilder().build().getService();
BlobId id = BlobId.fromGsUtilUri("gs://bucket/lolcat.csv");
byte[] bytes = s.readAllBytes(id);
```

**Comment by frankyn** [comment]
Closing based on discussion, there's a path forward using java-storage instead of java-storage-nio. Please reopen if Ben's follow-up does not address your question.
