### ISSUE TITLE
As of 2022-02-22 Automatic detection of requesterPays buckets is failing

### ISSUE THREAD

**Issue by BenWhitehead** [googleapis/java-storage-nio#824]
First observed on PR https://github.com/googleapis/java-storage-nio/pull/823 and visible in the integration tests related to Requester Pays ([build results](https://source.cloud.google.com/results/invocations/aaeb196d-16d2-45c9-8104-48dbc5a8c855/targets/github%2Fjava-storage-nio%2Fgoogle-cloud-nio%2Ftarget%2Ffailsafe-reports%2Fintegration%2Fcom.google.cloud.storage.contrib.nio.it.ITGcsNio/tests))

#### Environment details

1. this library
2. OS type and version: N/A
3. Java version: N/A
4. version(s): all released prior to 2022-02-22

#### Code example

https://github.com/googleapis/java-storage-nio/blob/417704a68c9fe8ad618300d23209364066bd9826/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java#L310-L316

#### External references such as API reference guides

It seems the error message response changed subtly
```diff
- Bucket is requester pays bucket but no user project provided.
+ Bucket is a requester pays bucket but no user project provided.
```

According to [public documentation](https://cloud.google.com/storage/docs/json_api/v1/status-codes#400_Bad_Request), we should expect the `reason` to be `userProjectMissing`, however it is `required` as can be seen in 
```json
{
  "error": {
    "code": 400,
    "message": "Bucket is a requester pays bucket but no user project provided.",
    "errors": [
      {
        "message": "Bucket is a requester pays bucket but no user project provided.",
        "domain": "global",
        "reason": "required"
      }
    ]
  }
}
```

Related from NodeJS https://github.com/googleapis/nodejs-storage/pull/1791/files

**Comment by lbergelson** [comment]
I think the underlying issue is here. 
https://github.com/googleapis/java-storage-nio/blob/fc0f8a1acecb7908849cfbfb3b1ad258f0787a32/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java#L963-L975

It always falls into the catch block which then tries to match against that changed string.  I think it shouldn't be falling into the catch block and instead the call to get(bucketName) should include an option specifying the project name which should keep it from throwing an exception.  It seems like a bug that was previously covered up by the catch clause.
` Boolean isRP = storage.get(bucketName).requesterPays(); `

**Comment by lbergelson** [comment]
Ignore that.  It seems that throwing the exception is necessary because it's attempting to find requester pays status without providing the user account to avoid access charges in the case where it wasn't requester pays.

It seems like there needs to be a more robust mechanism of determining if this is a requester pays bucket than scraping the exception message after trying to connect.  This mechanism also causes problems because it requires the somewhat unusual `storage.buckets.get` permission which is not necessary for reading the actual content of the bucket.  So users need more permissions than necessary when trying to read from a requester pays bucket because the test to see if it IS a requester pays bucket requires additional permissions than actually accessing the file they want.  This has caused continual confusion for our users.

Is there either:  
A) a way to query the requester pays status of a bucket that doesn't require the user to be authenticated in the case where it is requester pays
B) a way to make this ignore querying requester pays status and just falling back to connecting with a user account when we get back an error that says it is requester pays?

**Comment by droazen** [comment]
This issue is unfortunately breaking large numbers of our production workflows. I hate to suggest this, but perhaps for now we could grit our teeth and add the missing "a" into the message it's looking for to get it working again, and open a separate ticket to research / implement a more robust mechanism for detecting requester pays status. Unless someone already knows of a more robust way?

Once a patch is in for this issue, would it be possible to get a release of the library with the fix?
